name: karabiner_grabber

targets:
  karabiner_grabber:
    settings:
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../vendor/cget/include
        - ../../vendor/Karabiner-DriverKit-VirtualHIDDevice/include
      HEADER_SEARCH_PATHS:
        - include
        - ../../share
    type: tool
    platform: macOS
    deploymentTarget: 11.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=c++20'
      - path: ../../vendor/cget/src/pqrs/osx/process_info
      - path: ../../vendor/cget/src/pqrs/osx/workspace/impl/objc.m
    dependencies:
      - framework: CoreGraphics.framework
      - framework: CoreServices.framework
      - framework: IOKit.framework
