name: Karabiner-Menu

targets:
  Karabiner-Menu:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-Menu
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../vendor/cget/include
      HEADER_SEARCH_PATHS:
        - ../lib/KarabinerKit/include
        - ../../lib/libkrbn/include
      OTHER_LDFLAGS:
        - -L../lib/KarabinerKit/build/Release
        - -L../../lib/libkrbn/build/Release
        - -lKarabinerKit
        - -lkrbn
      SWIFT_OBJC_BRIDGING_HEADER: src/Bridging-Header.h
    type: application
    platform: macOS
    deploymentTarget: 11.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
      - path: ../share/swift
        compilerFlags:
          - -Wall
          - -Werror
      - path: ../../vendor/cget/src/pqrs/osx/process_info
      - path: Resources
        excludes:
          - .gitignore
          - '*.plist.in'
      - path: ../share/Resources/app.icns
    dependencies:
      - sdk: libc++.tbd
