name: karabiner_console_user_server

targets:
  karabiner_console_user_server:
    settings:
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../vendor/cget/include
        - ../../vendor/Karabiner-DriverKit-VirtualHIDDevice/include
      HEADER_SEARCH_PATHS:
        - include
        - ../../share
    type: tool
    platform: macOS
    deploymentTarget: 11.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=c++20'
      - path: ../../vendor/cget/src/pqrs/osx/frontmost_application_monitor
      - path: ../../vendor/cget/src/pqrs/osx/process_info
    dependencies:
      - framework: Carbon.framework
