name: Karabiner-EventViewer

packages:
  SwiftShell:
    url: https://github.com/kareman/SwiftShell
    from: 5.1.0

targets:
  Karabiner-EventViewer:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-EventViewer
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../vendor/cget/include
      HEADER_SEARCH_PATHS:
        - ../../lib/libkrbn/include
      OTHER_LDFLAGS:
        - -L../../lib/libkrbn/build/Release
        - -lkrbn
      SWIFT_OBJC_BRIDGING_HEADER: src/Bridging-Header.h
    type: application
    platform: macOS
    deploymentTarget: 11.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
      - path: ../share/swift
        compilerFlags:
          - -Wall
          - -Werror
      - path: ../../vendor/cget/src/pqrs/osx/process_info
      - path: Resources
        excludes:
          - .gitignore
          - '*.orig.png'
          - '*.plist.in'
    dependencies:
      - sdk: libc++.tbd
      - package: SwiftShell
